volumes:
  postgres-data:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092, CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  productdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      
  userdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
  
  coursedb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: course
  
  credentialdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54323:5432
    environment:
      POSTGRES_USER: credential
      POSTGRES_PASSWORD: credential   
  
  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080
