spring.kafka.bootstrap-servers=localhost:19092
server.port=18083
usersService.url=http://localhost:18082/users
usersService.getUsersToAlert.url=http://localhost:18082/users/toAlert?productId={productId}&availableOnDate={availableOnDate}
productService.getProductDetails.url=http://localhost:18081/products/{productId}
microcredentialService.getMicrocredentialDetails.url=http://localhost:18085/microcredentials/{microcredentialId}