spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.batch.jdbc.initialize-schema=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:54322/course
spring.datasource.username=course
spring.datasource.password=course
server.port=18084
server.error.include-message=always
userService.getUserByEmail.url=http://localhost:18082/users/byEmail/{email}
credentialService.create.url=http://localhost:18085/microcredentials/request